version: '3.6'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      DATABASE_URI: postgresql://user:password@database:5432/blog
    volumes:
    - ./blog:/app/blog
    ports:
      - 8080:5000
    depends_on:
    - database

  database:
    image: postgres:12
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  pgdata: